"""Rules Beyond deterministic engine package."""

from .dynamic_rule_controller import (
    RULE_PHASE_INTERVAL,
    DynamicMatchState,
    DynamicRoundResult,
    DynamicRuleController,
    DynamicRulePhaseResult,
    DynamicStartResult,
    RulePhaseOutcome,
)
from .engine import GameEngine, RoundResolution
from .model import (
    Action,
    Direction,
    GameConfig,
    GameState,
    MatchResult,
    Position,
    Team,
    UnitState,
    Weapon,
    initial_state,
    terminal_utility,
)
from .natural_language_rule_adapter import (
    MAX_MODEL_OUTPUT_CHARS,
    SYSTEM_PROMPT_V0_1,
    NaturalLanguageRuleAdapter,
    NaturalLanguageTranslation,
    RuleCandidateModel,
    TranslationStatus,
)
from .rule_dsl import (
    RuleAST,
    RuleCondition,
    RuleConditionType,
    RuleDuration,
    RuleEffect,
    RuleEffectType,
    RuleTarget,
    RuleWeapon,
)
from .rule_engine import RuleAwareGameEngine, RuleEffectiveStats, RuleRoundResolution
from .rule_runtime import (
    PublicRuleHistory,
    RuleEvaluator,
    RuleModifiers,
    initial_public_rule_histories,
    update_public_rule_histories,
)
from .rule_validator import RuleValidator, ValidationIssue, ValidationResult

__all__ = [
    "Action",
    "Direction",
    "DynamicMatchState",
    "DynamicRoundResult",
    "DynamicRuleController",
    "DynamicRulePhaseResult",
    "DynamicStartResult",
    "GameConfig",
    "GameEngine",
    "GameState",
    "MAX_MODEL_OUTPUT_CHARS",
    "MatchResult",
    "NaturalLanguageRuleAdapter",
    "NaturalLanguageTranslation",
    "Position",
    "PublicRuleHistory",
    "RULE_PHASE_INTERVAL",
    "RoundResolution",
    "RuleAST",
    "RuleAwareGameEngine",
    "RuleCandidateModel",
    "RuleCondition",
    "RuleConditionType",
    "RuleDuration",
    "RuleEffect",
    "RuleEffectType",
    "RuleEffectiveStats",
    "RuleEvaluator",
    "RuleModifiers",
    "RulePhaseOutcome",
    "RuleRoundResolution",
    "RuleTarget",
    "RuleValidator",
    "RuleWeapon",
    "SYSTEM_PROMPT_V0_1",
    "Team",
    "TranslationStatus",
    "UnitState",
    "ValidationIssue",
    "ValidationResult",
    "Weapon",
    "initial_public_rule_histories",
    "initial_state",
    "terminal_utility",
    "update_public_rule_histories",
]
