"""Rules Beyond deterministic engine package."""

from .dynamic_rule_controller import (
    DynamicContinueResult,
    DynamicMatchState,
    DynamicRoundResult,
    DynamicRuleController,
    DynamicRuleSubmissionResult,
    DynamicStartResult,
    IntermissionOutcome,
)
from .engine import GameEngine, RoundResolution
from .mimo_rule_provider import (
    DEFAULT_MIMO_API_KEY_ENV,
    DEFAULT_MIMO_BASE_URL_ENV,
    DEFAULT_MIMO_MODEL_ENV,
    DEFAULT_MIMO_RULE_MODEL,
    MIMO_TOKEN_PLAN_CN_BASE_URL,
    MimoProviderError,
    MimoRuleCandidateModel,
)
from .model import (
    Action,
    Direction,
    GameConfig,
    GameState,
    MatchResult,
    Position,
    Team,
    UnitState,
    Weapon,
    initial_state,
    terminal_utility,
)
from .natural_language_rule_adapter import (
    MAX_MODEL_OUTPUT_CHARS,
    SYSTEM_PROMPT_V0_1,
    NaturalLanguageRuleAdapter,
    NaturalLanguageTranslation,
    NoCandidateReason,
    RuleCandidateModel,
    TranslationStatus,
)
from .openai_compatible_provider import (
    OpenAICompatibleModel,
    OpenAICompatibleProviderError,
)
from .rule_dsl import (
    RuleAST,
    RuleCondition,
    RuleConditionType,
    RuleDuration,
    RuleEffect,
    RuleEffectType,
    RuleTarget,
    RuleWeapon,
)
from .rule_engine import RuleAwareGameEngine, RuleEffectiveStats, RuleRoundResolution
from .rule_runtime import (
    PublicRuleHistory,
    RuleEvaluator,
    RuleModifiers,
    initial_public_rule_histories,
    update_public_rule_histories,
)
from .rule_validator import RuleValidator, ValidationIssue, ValidationResult
from .zhipu_rule_provider import (
    DEFAULT_ZHIPU_API_KEY_ENV,
    DEFAULT_ZHIPU_MODEL_ENV,
    DEFAULT_ZHIPU_RULE_MODEL,
    ZHIPU_CHAT_COMPLETIONS_URL,
    ZhipuProviderError,
    ZhipuRuleCandidateModel,
)

__all__ = [
    "Action",
    "DEFAULT_MIMO_API_KEY_ENV",
    "DEFAULT_MIMO_BASE_URL_ENV",
    "DEFAULT_MIMO_MODEL_ENV",
    "DEFAULT_MIMO_RULE_MODEL",
    "DEFAULT_ZHIPU_API_KEY_ENV",
    "DEFAULT_ZHIPU_MODEL_ENV",
    "DEFAULT_ZHIPU_RULE_MODEL",
    "Direction",
    "DynamicContinueResult",
    "DynamicMatchState",
    "DynamicRoundResult",
    "DynamicRuleController",
    "DynamicRuleSubmissionResult",
    "DynamicStartResult",
    "GameConfig",
    "GameEngine",
    "GameState",
    "IntermissionOutcome",
    "MAX_MODEL_OUTPUT_CHARS",
    "MIMO_TOKEN_PLAN_CN_BASE_URL",
    "MatchResult",
    "MimoProviderError",
    "MimoRuleCandidateModel",
    "NaturalLanguageRuleAdapter",
    "NaturalLanguageTranslation",
    "NoCandidateReason",
    "OpenAICompatibleModel",
    "OpenAICompatibleProviderError",
    "Position",
    "PublicRuleHistory",
    "RoundResolution",
    "RuleAST",
    "RuleAwareGameEngine",
    "RuleCandidateModel",
    "RuleCondition",
    "RuleConditionType",
    "RuleDuration",
    "RuleEffect",
    "RuleEffectType",
    "RuleEffectiveStats",
    "RuleEvaluator",
    "RuleModifiers",
    "RuleRoundResolution",
    "RuleTarget",
    "RuleValidator",
    "RuleWeapon",
    "SYSTEM_PROMPT_V0_1",
    "Team",
    "TranslationStatus",
    "UnitState",
    "ValidationIssue",
    "ValidationResult",
    "Weapon",
    "ZHIPU_CHAT_COMPLETIONS_URL",
    "ZhipuProviderError",
    "ZhipuRuleCandidateModel",
    "initial_public_rule_histories",
    "initial_state",
    "terminal_utility",
    "update_public_rule_histories",
]
